services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A web_app.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"